services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: falcontouch
      POSTGRES_PASSWORD: falcontouch
      POSTGRES_DB: falcontouch_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Postgres: "${POSTGRES_CONN}"
      ConnectionStrings__Redis: "redis:6379"
      Jwt__Key: "${JWT__KEY}"
      Jwt__Issuer: "FalconTouch.Api"
    depends_on:
      - postgres
      - redis
    ports:
      - "5001:8080"

  # angular:
  #   build:
  #     context: .
  #     dockerfile: angular.Dockerfile
  #   depends_on:
  #     - api
  #   ports:
  #     - "4200:80"
